version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env
  backend:
    build: ./mybackend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mybackend:/mybackend
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./myfrontend
    container_name: frontend
    command: npm run start
    volumes:
      - ./myfrontend:/myfrontend
    ports:
      - "80:80"
    depends_on:
      - backend